export const SET_LIST_USERS = 'set_list_users'
export const SET_USER_DESTINATION = 'set_user_destination'
export const SET_MESSAGES = 'set_messages'
export const ADD_MESSAGE = 'add_message'
export const SET_NOTIFICATION = 'set_notification'
